### ISSUE TITLE
Hosting em um ESP

### ISSUE THREAD

**Issue by vmesel** [belimawr/portunhol#1]
Será que seria possível colocar um destes em um ESP em conjunto do bot do nosso querido amigo Fabs para podermos testar o comportamento do chip?

**Comment by belimawr** [comment]
Uma coisa de cada vez:
1. Colocar para rodar num ESP (é fácil, desde que o ESP já esteja rodando o MicroPython).
2. Integrar isso com o bot do telegram no ESP. Também não deve ser difícil já que o bot é essencialmente uma API/Interface HTTP
